name: Deploy production

# We deploy production only when the main branch is updated.
on:
  push:
    branches:
      - 'main'


jobs:
  deployment:
    runs-on: ubuntu-latest
    # We fetch the secrets from the 'Deploy' environment. 
    environment: Deploy
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: 22
        script:  |
          cd /services/prod
          ./backup.sh
          docker-compose down
          docker-compose up -d --build
          cd ./src
          git fetch
          git checkout $GITHUB_REF
          git reset -- hard
          git switch -
          git pull origin $GITHUB_SHA
          cd ..
          docker-compose down
          docker-compose up -d --build
