# This is a basic workflow that is manually triggered

name: Deploy staging

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - 'develop'
    tags:
    - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Deploy
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: 22
        script:  |
          cd /services/staging/src
          git checkout $GITHUB_REF
          git pull
          cd ..
          docker-compose down
          cp /backups/restore/latest.sql db/startup.sql
          docker-compose up -d --build
