name: Tailwind Check

on: 
  pull_request:
      branches: 
        - main
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        cd jstoolchain
        npm install
    - name: Check tailwind compile
      run: |
        cd jstoolchain/
        npx tailwindcss -c tailwind.config.js -o ../static/css/tailwind/gen.css
        cd ..
        git status
        git diff-index HEAD --quiet -- ./static

