name: Tailwind Check

on: 
  pull_request:
      branches: 
        - main
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apt install make npm
        cd jstoolchain
        npm install
    - name: Check tailwind compile
      run: |
        make tailwind-compile
        git status
        git diff-index HEAD --quiet -- ./static

